### ISSUE TITLE
Extracting name of the class from "params" (Classes.update)?

### ISSUE THREAD

**Issue by mkucharz** [Syncano/syncano4-js#3]
Now I have to do something this to update my class:
```javascript

var params = {
   'name': 'Book',
   'description': 'My new class to storing Books',
   'schema': schema
};

syncano.Classes.update("Book", params)
```
It would be great to extract name from `params` to make it more consistent with `Class.create`:
```javascript

var params = {
   'name': 'Book',
   'description': 'My new class to storing Books',
   'schema': schema
};

syncano.Classes.update(params)
```
From the other hand `Classes.remove` works the same way as `Class.update`, so maybe we should change `Class.create` to:
```javascript

var params = {
   'description': 'My new class to storing Books',
   'schema': schema
};

syncano.Classes.create("Book", params)
```
What do you think?

**Comment by gietek** [comment]
The idea behing method params is:
create(WHAT)
update(WHAT, HOW)
remove(WHAT)

In case of create method - WHAT means full class / instance / etc definition. In case of remove - WHAT means identifier (id / name / slug / etc) or full object. In case of update there are two logical arguments - first is what we want to update (id / name / slug / etc), second - changed fields. This makes perfect sense for me.
Also, this was designed when changing the class name was possible, so it was the only way to pass two class names - current and new.

**Comment by mkucharz** [comment]
Thanks @gietek, let's leave it for a while and see what others think about that.

**Comment by lifcio** [comment]
I see it also as inconsistent, but I understand the argument about changing class name - the fact that we're not doing it now, is not the reason to change the concept, because the functionality will be implemented in the future.

@gietek What if we had 
```js
syncano.Classes.update(params)
//and 
syncano.Classes.update(name, params)
```
 - in case "name" is not passed, it would be taken from the "params"? So it would basically be a wrapper around current implementation, and as long as changing names is not possible, we consider it a private API and won't mention it in docs, tutorials etc.

Other solution would be to have 
```js
params = {
   name: "Book", 
   newName: "Notebook"
}
```

But I'm not sure - it might be more confusing. What do you think?

**Comment by gietek** [comment]
@lifcio Solution with "name" and "newName" is very bad. If someone uses high-level frameworks such as Backbone, will have to change the keys with every update. We don't want this.

As for the first option - I'm doing sample todo app using this library right now. I'll see which approach is easier to use and then make my decision.

**Comment by gietek** [comment]
@lifcio Done. Now you can use
```
syncano.Classes.update(params)
```
or
```
syncano.Classes.update(name, params)
```
